version: "3"

services:

    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Tokyo
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf

    react:
        build: ./react/
        container_name: react
        volumes:
            - ../app:/mnt/app/
        working_dir: /mnt/app/
        command: sh -c "npm install && npm run start"
        ports:
            - "3000:3000"

    express:
        build: ./express
        container_name: express
        volumes:
            - ../api:/mnt/api/
        working_dir: /mnt/api/
        tty: true
        command: sh -c "npm install"
        ports:
            - "5000:5000"

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ../app/:/var/www/
        working_dir: /var/www/